### ISSUE TITLE
AWS Policy for DeployFish

### ISSUE THREAD

**Issue by Jamie-BitFlight** [caltechads/deployfish#12]
Have you written a policy for an IAM user that can run DeployFish that has only enough permissions to do all of the deployfish commands?
If so would you be able to add it to the Repo in the examples folder?

I've so far attached these two pre baked policies:

AmazonECS_FullAccess
AmazonEC2ContainerRegistryPowerUser

And I am getting this error:
```
+ deploy -i --filename ./_config/deployfish.yml update staging
Traceback (most recent call last):
  File "/usr/local/bin/deploy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/deployfish/dplycli.py", line 644, in main
    cli(obj={})
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/deployfish/dplycli.py", line 258, in update
    service = Service(yml=Config(filename=ctx.obj['CONFIG_FILE'], env_file=ctx.obj['ENV_FILE'], import_env=ctx.obj['IMPORT_ENV']).get_service(service_name))
  File "/usr/local/lib/python2.7/site-packages/deployfish/config.py", line 38, in __init__
    self.terraform = Terraform(yml=self.__raw['terraform'])
  File "/usr/local/lib/python2.7/site-packages/deployfish/terraform.py", line 12, in __init__
    self.load_yaml(yml)
  File "/usr/local/lib/python2.7/site-packages/deployfish/terraform.py", line 31, in load_yaml
    self.get_terraform_state(yml['statefile'])
  File "/usr/local/lib/python2.7/site-packages/deployfish/terraform.py", line 24, in get_terraform_state
    tfstate = self._get_state_file_from_s3(state_file_url)
  File "/usr/local/lib/python2.7/site-packages/deployfish/terraform.py", line 20, in _get_state_file_from_s3
    state_file = key.get()["Body"].read().decode('utf-8')
  File "/usr/local/lib/python2.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the GetObject operation: Access Denied
```

Sorry for pinging you so often!

**Comment by cmalek** [comment]
This is what we use for our AWS CodeBuild role, and this is sufficient for `deploy update` and `deploy create`.    Probably missing something in order for `deploy delete` to work properly.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "ecs:CreateService",
                "ecs:Describe*",
                "ecs:List*",
                "ecs:UpdateService",
                "ecs:RegisterTaskDefinition",
                "ecs:RunTask",
                "ecs:StartTask",
                "ecs:StopTask",
                "ecs:SubmitTaskStateChange",
                "ecr:ListImages",
                "application-autoscaling:*",
                "cloudwatch:DescribeAlarms",
                "cloudwatch:DeleteAlarms",
                "cloudwatch:PutMetricAlarm",
                "elasticloadbalancing:Describe*",
                "iam:PassRole"
            ],
            "Resource": "*",
            "Effect": "Allow"
        }
    ]
}
```

You will also need specific policies to allow you to read/write your app's ParameterStore values and to use any KMS keys you're using to encrypt the secure ParameterStore values.
