### ISSUE TITLE
missing dependency - requests

### ISSUE THREAD

**Issue by chrisLeeTW** [caltechads/deployfish#18]
If you install deployfish with pip and clear enviroment (such docker images.)

And exec command `deploy --help`

you will get error message

```
Traceback (most recent call last):
  File "/usr/bin/deploy", line 7, in <module>
    from deployfish.dplycli import main
  File "/usr/lib/python2.7/site-packages/deployfish/dplycli.py", line 14, in <module>
    from deployfish.config import Config
  File "/usr/lib/python2.7/site-packages/deployfish/config.py", line 6, in <module>
    from deployfish.terraform import Terraform
  File "/usr/lib/python2.7/site-packages/deployfish/terraform.py", line 2, in <module>
    import requests
ImportError: No module named requests
```

**Comment by cmalek** [comment]
Thanks!  The version I just released with rv-cohall's Service Discovery changes should fix this.  That would be version 0.20.0.
