### ISSUE TITLE
KeyError: 'serviceRegistries'

### ISSUE THREAD

**Issue by afosterw** [caltechads/deployfish#23]
With config:

```
services:
  - name: test-service1
    cluster: test-cluster1
    count: 1
    family: test1
    network_mode: bridge
    containers:
      - name: test_container1
        image: <account_id_removed>.dkr.ecr.us-west-2.amazonaws.com/test_service:dev.latest
        cpu: 128
        memory: 512
        ports:
          - "80"
          - "443"
```

```
Traceback (most recent call last):
  File "/home/afosterw/.virtualenvs/lovepop-cli/bin/deploy", line 11, in <module>
    load_entry_point('deployfish', 'console_scripts', 'deploy')()
  File "/home/afosterw/lovepop/deployfish/deployfish/dplycli.py", line 656, in main
    cli(obj={})
  File "/home/afosterw/.virtualenvs/lovepop-cli/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/afosterw/.virtualenvs/lovepop-cli/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/afosterw/.virtualenvs/lovepop-cli/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/afosterw/.virtualenvs/lovepop-cli/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/afosterw/.virtualenvs/lovepop-cli/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/afosterw/.virtualenvs/lovepop-cli/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/afosterw/lovepop/deployfish/deployfish/dplycli.py", line 196, in create
    service.create()
  File "/home/afosterw/lovepop/deployfish/deployfish/aws/ecs.py", line 1315, in create
    self.from_aws()
  File "/home/afosterw/lovepop/deployfish/deployfish/aws/ecs.py", line 1278, in from_aws
    if self.__aws_service['serviceRegistries']:
KeyError: 'serviceRegistries'
```

**Comment by afosterw** [comment]
It happens on info, create and delete:

boto==2.46.1
boto3==1.5.18
botocore==1.8.39

I fixed locally with this change:
`diff --git a/deployfish/aws/ecs.py b/deployfish/aws/ecs.py
index d472abe..724cf60 100644
--- a/deployfish/aws/ecs.py
+++ b/deployfish/aws/ecs.py
@@ -1273,7 +1273,7 @@ class Service(object):
                 for t in self.tasks.values():
                     t.from_aws(helpers[t.family])
 
-            if self.__aws_service['serviceRegistries']:
+            if 'serviceRegistries' in self.__aws_service:
                 self.serviceDiscovery = ServiceDiscovery(self.service_discovery[0]['registryArn'])
             else:
                 self.serviceDiscovery = None
`

**Comment by cmalek** [comment]
Ah, those are old versions of boto3 and botocore.  Could you update to latest and try again?

Current is:

boto3==1.7.49
botocore==1.10.49

You need to keep botocore and boto3 up to date so they can match changes to the upstream AWS API.

**Comment by cmalek** [comment]
Yes, looking through the changelogs for botocore, the 'serviceRegistries' keyword was added in  botocore==1.9.15, so the minimum requirement for boto3 looks like it would be 1.6.15.

I'll update the requirements appropriately.

**Comment by cmalek** [comment]
I've released the requirements change to PyPi as deployfish==0.21.1 .

**Comment by afosterw** [comment]
Thanks! I've updated to the latest boto/botocore and it's resolved on my
end.
